### ISSUE TITLE
Variables from metadata in text

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#110]
The syllabus mentions the values defined in `metadata.yml` several times. Variables like `schema`, `level`, and `title` are repeated several times in chapter 0 of every syllabus. It would be great to reference them as variables to avoid text duplication and mistakes.

Acceptance criteria:

1. Variables from `metadata.yml` can be referenced in text using syntax `$variable`
2. Variables are substituted in all document formats, including DOCX
3. Values are not substituted if not defined in `metdata.yml` and if escaped `\$variable`
4. Users can define any variable in `metadata.yml` to be referenced in the text
5. Documentation in this repository is updated
6. Template repository and other product repositories are updated by @danopolan

**Comment by Witiko** [comment]
> Variables from metadata.yml can be referenced in text using syntax `$variable`

It also seems useful to be able to write variables that are not necessarily followed by a whitespace. For example, we would not be able to write the following: `_This is empasized text: $variable_`, because `variable_` would be incorrectly understood as the name of the variable.

Therefore, let's perhaps also support the syntax `${variable}`. This syntax allows us to write variables that are not necessarily followed by a whitespace: `_This is empasized text: ${variable}_`. We can support `${variable}` in addition to or instead of `$variable`. Personally, I lean towards supporting just `${variable}`, so that there are fewer things to remember and less potential for unexpected replacements elsewhere in the text.

> Users can define any variable in `metadata.yml` to be referenced in the text

This seems like something that would prevent us from checking metadata against the YAML schema. Let's perhaps have a separate section of `metadata.yml` for user-defined variables named, for example, `variables` or `vars`?

We may also wish to add prefix such as `${metadata.variable}` for top-level metadata variables and `${metadata.variables.variable}` for user-defined variables? This would 1) disambiguate top-level metadata from user-defined variables, 2) leave us more options for adding other variable namespaces in the future, and 3) create less potential for unexpected replacements elsewhere in the text. However, it also makes typing the variables less convenient for users; what do you think, @danopolan?

> Values are not substituted if not defined in `metadata.yml` and if escaped `\$variable`

In the former case (an undefined variable is used), we may want to raise an error during the validation of MD files to help authors catch typos in variable names.

**Comment by danopolan** [comment]
> Therefore, let's perhaps also support the syntax `${variable}`.

Agree. Syntax `${variable}` is better since it prevents future issues.



> We may also wish to add prefix such as `${metadata.variable}` for top-level metadata variables and `${metadata.variables / vars.variable}` for user-defined variables?

I am not sure I follow your thoughts here.

> In the former case (an undefined variable is used), we may want to raise an error during the validation of MD files to help authors catch typos in variable names before compilation.

Definitely, we would like to raise an exception in validation.

**Comment by Witiko** [comment]
> I am not sure I follow your thoughts here.

Let me give some more examples of my thoughts and concerns on this point:

I suggest that, instead of `${variable}`,  users would write `${metadata.variable}` or `${metadata.variables.variable}`.

Adding a prefix would disambiguate variable access. For example, assume that we have the following file `metadata.yml`:

``` yaml
organization: ISTQB®
schema: Certified Tester
level: Foundation Level
title: Example Document
prefix: EXMPL
code: CT-EXMPL
type: Syllabus
version: v0.1
date: 2024/06/04
release: For internal use only
logo: istqb-logo-default
language: en
line-numbers: false
compatibility: |
  Compatible with Syllabus on Foundation and Advanced Levels,
  and Specialist Modules
provided-by:
# 3rd-party organizations with logos
- name: Czech and Slovak Quality Board
  logo: casqb-logo-vertical
- name: Polish Testing Board
  logo: sjsi-logo
# 3rd-party organizations without logos
- name: International Requirements Engineering Board  # or just:
- Hungarian Testing Board
# User-defined variables
variables:
  code: foo
  bar: baz
```

Then, users can write `${metadata.code}` for "CT-EXMPL" and `${metadata.variables.code}` for "foo". If they wrote just `${code}`, then it would be unclear which variable the users are trying to access. We could also solve this by having the user-defined variables at the top level of `metadata.yml` and not in section `variables:`, but we should reserve the top level for future metadata rather than user-defined variables.

Besides disambiguation, adding a prefix would also leave us with more options for using different variable namespaces. For example, we may decide that users might write `${sections.section_id}` and have it replaced with the title of a section with id `#section_id`. Alternatively, we may want to allow users to access learning objectives and business outcomes by writing `${learning_objectives.objective}` or `${business_outcomes.outcome}`. We can't do this easily if users write just `${variable}`.

Lastly, writing `${metadata.variable}` or `${metadata.variables.variable}` seems more self-documenting than `${variable}`. In the first two code examples, it seems clear where the variable comes from even without reading the documentation.
