### ISSUE TITLE
Sample Exam: Convert integers in questions answers into strings

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#25]
Integers in questions answers are not accepted, since it requires string.

Currently, we have to put integers into quotes like following
```yaml
answers:
      a: '5'
      b: '12'
```

It would be nice to enable direct integer inputs like 
```yaml
answers:
      a: 5
      b: 12
```
