### ISSUE TITLE
CTAL-TA Traceability matrix table in LaTeX

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#61]
Despite the provided code in #51 [comment](https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145716482) I am not able to pull the traceability matrix for CTAL TA and I am not able to find an issue with the code.

Initially I have only tried the [first part with BOs](https://github.com/istqborg/istqb-ctal-ta/commit/a7801f604d824a5a404e5a9185e5de0ecbd50d37), but the pipeline failed and cannot find out the problem.

Later I have [added all LOs](https://github.com/istqborg/istqb-ctal-ta/commit/18e3d5fd285231e73d9d29e0ec4f59a3342c6886), which makes the full table, but of course, with the same result.

Can you please:

1. Find the issue(s) I made
2. Suggest how to debug pipeline failures for LaTeX tables.
3. Suggest how to debug LaTeX tables creation. Is it possible to use some online tooling? Or syntax checker? Overleaf didn't worked for me :(
4. Add these hints to the example document.

**Comment by Witiko** [comment]
> Initially I have only tried the [first part with BOs](https://github.com/istqborg/istqb-ctal-ta/commit/a7801f604d824a5a404e5a9185e5de0ecbd50d37), but the pipeline failed and cannot find out the problem.

You have one extra cell on one of the lines, please see https://github.com/istqborg/istqb-ctal-ta/commit/a7801f604d824a5a404e5a9185e5de0ecbd50d37#r142825658.

> Later I have [added all LOs](https://github.com/istqborg/istqb-ctal-ta/commit/18e3d5fd285231e73d9d29e0ec4f59a3342c6886), which makes the full table, but of course, with the same result.

The full table from commit https://github.com/istqborg/istqb-ctal-ta/commit/18e3d5fd285231e73d9d29e0ec4f59a3342c6886 does not seem in line with the original assignment in https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145716482. Namely, the code assumes that the table will fit on a single page and will only contain a single matrix. Both these assumptions seem broken by the code from commit https://github.com/istqborg/istqb-ctal-ta/commit/18e3d5fd285231e73d9d29e0ec4f59a3342c6886. If you need a table that would span across several pages, you can't use my original code from https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145716482 unless you break the table into several smaller tables, each of which should fit on a single page and be written in its own separate ```` ```{=tex} ```` block.

If all these tables follow a unified format, perhaps it would be easier for you to write them in YAML or Markdown instead of LaTeX. This would make it easier to read, write, and automatically validate these tables.

**Comment by Witiko** [comment]
> If all "traceability matrix" tables follow a unified format, perhaps it would be easier for you to write them in YAML or Markdown instead of LaTeX. This would make them easier to read, write, and automatically validate. Alternatively, I can produce the LaTeX tables for you if you provide me with screenshots or other examples of the expected output. However, this may slow you down depending on my availability; removing the need for writing tables in LaTeX should be significantly more time-efficient.

For example, I can encode the traceability matrix from https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145716482 with the following simple YAML document:

``` yaml
matrix:
  1:  [Understand what testing is and why it is beneficial, 6]
  2:  [Understand fundamental concepts of software testing, 22]
  3:  [Identify the test approach and activities to be implemented depending on the context of testing, 6]
  4:  [Assess and improve the quality of documentation, 9]
  5:  [Increase the effectiveness and efficiency of testing, 20]
  6:  [Align the test process with the software development lifecycle, 6]
  7:  [Understand test management principles, 6]
  8:  [Write and communicate clear and understandable defect reports, 1]
  9:  [Understand the factors that influence the priorities and efforts related to testing, 7]
  10: [Works par of a cross-functional, 8]
  11: [Know risks and benefits related to test automation, 5]
  12: [Identify essential skills required for testing, 5]
  13: [Understand the impact of risk on testing, 4]
  14: [Effectively report on test progress and quality, 4]
```

Both "FL" and "Foundation Level" are already part of the metadata from the original document and don't need to be specified.

However, your full table from commit https://github.com/istqborg/istqb-ctal-ta/commit/18e3d5fd285231e73d9d29e0ec4f59a3342c6886 indicates that a traceability matrix can be more complex and would require a more general YAML format. If you could help me understand the anatomy of a traceability matrix, we should be able to find a better input format than LaTeX.

**Comment by danopolan** [comment]
If there is a way how to create such a table easier than using LaTeX, that would be a much preferred.

The table is always a combination of LOs and BOs, and the table width and length depend on the number of BOs and LOs in the syllabus.

Attached, you can find the table for CTAL TA syllabus. All products follow this structure; just the content and respective sizes are different.

[ISTQB_CTAL-TA_Appendix B table.docx](https://github.com/user-attachments/files/15733243/ISTQB_CTAL-TA_Appendix.B.table.docx)

**Comment by Witiko** [comment]
I designed a YAML schema for writing traceability matrices:

``` yaml
business-outcomes: map(str(), key=str())
learning-objectives:
  sections: map(str(), key=any(str(), int()))
  objectives: map(include('objective'), key=str())
---
objective:
  description: str()
  k-level: str()
  business-outcomes: list(str())
```

For example, here is how we would write the traceability matrix from document [`ISTQB_CTAL-TA_Appendix B table.docx`](https://github.com/user-attachments/files/15733243/ISTQB_CTAL-TA_Appendix.B.table.docx):

``` yaml
business-outcomes:
  BO-TA1: Support and perform appropriate testing based on the software development lifecycle followed
  BO-TA2: Apply the principles of risk-based testing
  BO-TA3: Select and apply appropriate test techniques to support the achievement of test objectives
  BO-TA4: Provide documentation at appropriate levels of detail and quality
  BO-TA5: Determine the appropriate types of functional testing to be performed
  BO-TA6: Contribute to non-functional testing
  BO-TA7: Contribute to the prevention of defects
  BO-TA8: Improve the efficiency of the test process with the use of tools
  BO-TA9: Specify the requirements for test environments and test data
learning-objectives:
  sections:
    1: The Test Analyst’s Tasks in the Test Process
    1.1: Testing in the Software Development Lifecycle
    1.2: Involvement in the test activities
    1.3: Tasks related to work products
    2: The Test Analyst's Tasks in Risk-Based Testing
    2.1: Risk Analysis
    2.2: Risk Control
    3: Test Analysis and Design
    3.1: Data-based Techniques
    3.2: Behavior-Based Techniques
    3.3: Rule-Based Techniques
    3.4: Experience-Based Test Techniques
    3.5: Applying the Most Appropriate Test Techniques
    4: Testing Software Quality Characteristics
    4.1: Functional testing
    4.2: Usability testing
    4.3: Flexibility testing
    4.4: Compatibility testing
    5: Software Defect Prevention
    5.1: Defect prevention practices
    5.2: Supporting phase containment
    5.3: Mitigating the recurrence of defects
  objectives:
    TA-1.1.1:
      description: Summarize the involvement of the Test Analyst in different SDLCs
      k-level: K2
      business-outcomes: [BO-TA1]
    TA-1.2.1:
      description: Summarize the tasks performed by the TA as part of test analysis
      k-level: K2
      business-outcomes: [BO-TA1]
    TA-1.2.2:
      description: Summarize the tasks performed by the TA as part of test design
      k-level: K2
      business-outcomes: [BO-TA1]
    TA-1.2.3:
      description: Summarize the tasks performed by the TA as part of test implementation
      k-level: K2
      business-outcomes: [BO-TA1]
    TA-1.2.4:
      description: Summarize the tasks performed by the TA as part of test execution
      k-level: K2
      business-outcomes: [BO-TA1]
    TA-1.3.1:
      description: Differentiate between high-level and low-level test cases
      k-level: K2
      business-outcomes: [BO-TA4]
    TA-1.3.2:
      description: Explain the quality criteria for test cases
      k-level: K2
      business-outcomes: [BO-TA4]
    TA-1.3.3:
      description: Give examples of test environment requirements
      k-level: K2
      business-outcomes: [BO-TA4, BO-TA9]
    TA-1.3.4:
      description: Explain the test oracle problem and potential solutions
      k-level: K2
      business-outcomes: [BO-TA4, BO-TA9]
    TA-1.3.5:
      description: Give examples of test data requirements
      k-level: K2
      business-outcomes: [BO-TA4, BO-TA9]
    TA-1.3.6:
      description: Use keyword-driven testing to develop test scripts
      k-level: K2
      business-outcomes: [BO-TA1, BO-TA8]
    TA-1.3.7:
      description: Summarize the types of tools applied in managing the testware
      k-level: K2
      business-outcomes: [BO-TA8]
    TA-2.1.1:
      description: Summarize the test analyst’s contribution to product risk analysis
      k-level: K2
      business-outcomes: [BO-TA2]
    TA-2.2.2:
      description: Analyze the impact of changes to determine the scope of regression testing
      k-level: K4
      business-outcomes: [BO-TA2, BO-TA8]
    TA-3.1.1:
      description: Apply domain testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.1.2:
      description: Apply combinatorial testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.1.3:
      description: Summarize the benefits and limitaions of random testing
      k-level: K2
      business-outcomes: [BO-TA3]
    TA-3.2.1:
      description: Explain CRUD testing
      k-level: K2
      business-outcomes: [BO-TA3]
    TA-3.2.2:
      description: Apply state-based testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.2.3:
      description: Apply scenario-based testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.3.1:
      description: Apply decision table testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.3.2:
      description: Apply metamorphic testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.4.1:
      description: Prepare test charters for session-based testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.4.2:
      description: Prepare checklists supporting experience-based testing
      k-level: K3
      business-outcomes: [BO-TA3]
    TA-3.4.3:
      description: Give examples for benefits and limitations of crowd testing
      k-level: K2
      business-outcomes: [BO-TA3]
    TA-3.5.1:
      description: Select appropriate test techniques to mitigate product risks for a given situation
      k-level: K4
      business-outcomes: [BO-TA2, BO-TA3]
    TA-3.5.2:
      description: Explain the benefits of automating the test design
      k-level: K2
      business-outcomes: [BO-TA8]
    TA-4.1.1:
      description: Differentiate between functional correctness, functional appropriateness and functional completeness testing
      k-level: K2
      business-outcomes: [BO-TA5]
    TA-4.2.1:
      description: Explain how the test analyst contributes to usability testing
      k-level: K2
      business-outcomes: [BO-TA6]
    TA-4.3.1:
      description: Explain how the test analyst contributes to adaptability and installability testing
      k-level: K2
      business-outcomes: [BO-TA6]
    TA-4.4.1:
      description: Explain how the test analyst contributes to interoperability testing
      k-level: K2
      business-outcomes: [BO-TA3, BO-TA6]
    TA-5.1.1:
      description: Explain how the test analyst can contribute to defect prevention
      k-level: K2
      business-outcomes: [BO-TA7]
    TA-5.2.1:
      description: Use a model of the test object to detect anomalies in a specification
      k-level: K3
      business-outcomes: [BO-TA7]
    TA-5.2.2:
      description: Apply a review technique to a test basis document to find defects
      k-level: K3
      business-outcomes: [BO-TA7]
    TA-5.3.1:
      description: Analyze test results to identify potential improvements to defect detection
      k-level: K4
      business-outcomes: [BO-TA7]
    TA-5.3.2:
      description: Explain how defect classification supports root cause analysis
      k-level: K2
      business-outcomes: [BO-TA7]
```

Here is how an author would include the traceability matrix from file `matrix.yml` in a document:

``` tex
\markdownSetup {
  import = {
    istqb/syllabus = traceability-matrix,
  }
}
```
``` tex
\markdownInput[snippet=traceability-matrix]{matrix.yml}
```

This would produce the entire appendix with the traceability matrix:

![image](https://github.com/user-attachments/assets/f75bcd42-ec18-4ce2-9bf2-b31a2a740208)
![image](https://github.com/user-attachments/assets/f81d48b9-8ae9-440a-b865-d5f126aa02a8)
![image](https://github.com/user-attachments/assets/beeb24f2-3aeb-4cea-ac80-d23aca748815)
![image](https://github.com/user-attachments/assets/4d12fda1-a8dc-46ba-b0ab-f7627320f7da)
![image](https://github.com/user-attachments/assets/49a3ee31-37f0-4459-93a7-8c59a5053393)
